print("Haloo")
print("Perkenalkan nama saya rafli")
print("umur saya 18 tahun")
print("saya berasal dari kota bandung")
print("hobi saya adalah menonton film")
print("makanan favorit saya adalah eskrim")
print("selamat datang")